BEGIN;

-- Drop Tables
DROP IF EXISTS user;

-- Drop enums
DROP IF EXISTS user_role_enum;

CREATE TYPE user_role_enum AS ENUM(
    'admin',
    'manager',
    'driver'
);

CREATE TABLE user(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(32) NOT NULL,
    role user_role_enum NOT NULL
);

COMMIT;