BEGIN;

-- Drop Tables
DROP TABLE IF EXISTS app_user;

-- Drop enums
DROP TYPE IF EXISTS app_user_role_enum;

CREATE TYPE app_user_role_enum AS ENUM(
    'admin',
    'manager',
    'driver'
);

CREATE TABLE app_user(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(32) NOT NULL,
    role app_user_role_enum NOT NULL
);

COMMIT;